/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2alpha1 "github.com/galasa-dev/galasa-kubernetes-operator/pkg/apis/galasaecosystem/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGalasaCpsComponents implements GalasaCpsComponentInterface
type FakeGalasaCpsComponents struct {
	Fake *FakeGalasaV2alpha1
	ns   string
}

var galasacpscomponentsResource = schema.GroupVersionResource{Group: "galasa.dev", Version: "v2alpha1", Resource: "galasacpscomponents"}

var galasacpscomponentsKind = schema.GroupVersionKind{Group: "galasa.dev", Version: "v2alpha1", Kind: "GalasaCpsComponent"}

// Get takes name of the galasaCpsComponent, and returns the corresponding galasaCpsComponent object, and an error if there is any.
func (c *FakeGalasaCpsComponents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.GalasaCpsComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(galasacpscomponentsResource, c.ns, name), &v2alpha1.GalasaCpsComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaCpsComponent), err
}

// List takes label and field selectors, and returns the list of GalasaCpsComponents that match those selectors.
func (c *FakeGalasaCpsComponents) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.GalasaCpsComponentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(galasacpscomponentsResource, galasacpscomponentsKind, c.ns, opts), &v2alpha1.GalasaCpsComponentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2alpha1.GalasaCpsComponentList{ListMeta: obj.(*v2alpha1.GalasaCpsComponentList).ListMeta}
	for _, item := range obj.(*v2alpha1.GalasaCpsComponentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested galasaCpsComponents.
func (c *FakeGalasaCpsComponents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(galasacpscomponentsResource, c.ns, opts))

}

// Create takes the representation of a galasaCpsComponent and creates it.  Returns the server's representation of the galasaCpsComponent, and an error, if there is any.
func (c *FakeGalasaCpsComponents) Create(ctx context.Context, galasaCpsComponent *v2alpha1.GalasaCpsComponent, opts v1.CreateOptions) (result *v2alpha1.GalasaCpsComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(galasacpscomponentsResource, c.ns, galasaCpsComponent), &v2alpha1.GalasaCpsComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaCpsComponent), err
}

// Update takes the representation of a galasaCpsComponent and updates it. Returns the server's representation of the galasaCpsComponent, and an error, if there is any.
func (c *FakeGalasaCpsComponents) Update(ctx context.Context, galasaCpsComponent *v2alpha1.GalasaCpsComponent, opts v1.UpdateOptions) (result *v2alpha1.GalasaCpsComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(galasacpscomponentsResource, c.ns, galasaCpsComponent), &v2alpha1.GalasaCpsComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaCpsComponent), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGalasaCpsComponents) UpdateStatus(ctx context.Context, galasaCpsComponent *v2alpha1.GalasaCpsComponent, opts v1.UpdateOptions) (*v2alpha1.GalasaCpsComponent, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(galasacpscomponentsResource, "status", c.ns, galasaCpsComponent), &v2alpha1.GalasaCpsComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaCpsComponent), err
}

// Delete takes name of the galasaCpsComponent and deletes it. Returns an error if one occurs.
func (c *FakeGalasaCpsComponents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(galasacpscomponentsResource, c.ns, name), &v2alpha1.GalasaCpsComponent{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGalasaCpsComponents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(galasacpscomponentsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v2alpha1.GalasaCpsComponentList{})
	return err
}

// Patch applies the patch and returns the patched galasaCpsComponent.
func (c *FakeGalasaCpsComponents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.GalasaCpsComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(galasacpscomponentsResource, c.ns, name, pt, data, subresources...), &v2alpha1.GalasaCpsComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaCpsComponent), err
}
