/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2alpha1 "github.com/galasa-dev/galasa-kubernetes-operator/pkg/apis/galasaecosystem/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGalasaEngineControllerComponents implements GalasaEngineControllerComponentInterface
type FakeGalasaEngineControllerComponents struct {
	Fake *FakeGalasaV2alpha1
	ns   string
}

var galasaenginecontrollercomponentsResource = schema.GroupVersionResource{Group: "galasa.dev", Version: "v2alpha1", Resource: "galasaenginecontrollercomponents"}

var galasaenginecontrollercomponentsKind = schema.GroupVersionKind{Group: "galasa.dev", Version: "v2alpha1", Kind: "GalasaEngineControllerComponent"}

// Get takes name of the galasaEngineControllerComponent, and returns the corresponding galasaEngineControllerComponent object, and an error if there is any.
func (c *FakeGalasaEngineControllerComponents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.GalasaEngineControllerComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(galasaenginecontrollercomponentsResource, c.ns, name), &v2alpha1.GalasaEngineControllerComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaEngineControllerComponent), err
}

// List takes label and field selectors, and returns the list of GalasaEngineControllerComponents that match those selectors.
func (c *FakeGalasaEngineControllerComponents) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.GalasaEngineControllerComponentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(galasaenginecontrollercomponentsResource, galasaenginecontrollercomponentsKind, c.ns, opts), &v2alpha1.GalasaEngineControllerComponentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2alpha1.GalasaEngineControllerComponentList{ListMeta: obj.(*v2alpha1.GalasaEngineControllerComponentList).ListMeta}
	for _, item := range obj.(*v2alpha1.GalasaEngineControllerComponentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested galasaEngineControllerComponents.
func (c *FakeGalasaEngineControllerComponents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(galasaenginecontrollercomponentsResource, c.ns, opts))

}

// Create takes the representation of a galasaEngineControllerComponent and creates it.  Returns the server's representation of the galasaEngineControllerComponent, and an error, if there is any.
func (c *FakeGalasaEngineControllerComponents) Create(ctx context.Context, galasaEngineControllerComponent *v2alpha1.GalasaEngineControllerComponent, opts v1.CreateOptions) (result *v2alpha1.GalasaEngineControllerComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(galasaenginecontrollercomponentsResource, c.ns, galasaEngineControllerComponent), &v2alpha1.GalasaEngineControllerComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaEngineControllerComponent), err
}

// Update takes the representation of a galasaEngineControllerComponent and updates it. Returns the server's representation of the galasaEngineControllerComponent, and an error, if there is any.
func (c *FakeGalasaEngineControllerComponents) Update(ctx context.Context, galasaEngineControllerComponent *v2alpha1.GalasaEngineControllerComponent, opts v1.UpdateOptions) (result *v2alpha1.GalasaEngineControllerComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(galasaenginecontrollercomponentsResource, c.ns, galasaEngineControllerComponent), &v2alpha1.GalasaEngineControllerComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaEngineControllerComponent), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGalasaEngineControllerComponents) UpdateStatus(ctx context.Context, galasaEngineControllerComponent *v2alpha1.GalasaEngineControllerComponent, opts v1.UpdateOptions) (*v2alpha1.GalasaEngineControllerComponent, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(galasaenginecontrollercomponentsResource, "status", c.ns, galasaEngineControllerComponent), &v2alpha1.GalasaEngineControllerComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaEngineControllerComponent), err
}

// Delete takes name of the galasaEngineControllerComponent and deletes it. Returns an error if one occurs.
func (c *FakeGalasaEngineControllerComponents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(galasaenginecontrollercomponentsResource, c.ns, name), &v2alpha1.GalasaEngineControllerComponent{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGalasaEngineControllerComponents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(galasaenginecontrollercomponentsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v2alpha1.GalasaEngineControllerComponentList{})
	return err
}

// Patch applies the patch and returns the patched galasaEngineControllerComponent.
func (c *FakeGalasaEngineControllerComponents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.GalasaEngineControllerComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(galasaenginecontrollercomponentsResource, c.ns, name, pt, data, subresources...), &v2alpha1.GalasaEngineControllerComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaEngineControllerComponent), err
}
