/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2alpha1 "github.com/galasa-dev/galasa-kubernetes-operator/pkg/client/clientset/versioned/typed/galasaecosystem/v2alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeGalasaV2alpha1 struct {
	*testing.Fake
}

func (c *FakeGalasaV2alpha1) GalasaApiComponents(namespace string) v2alpha1.GalasaApiComponentInterface {
	return &FakeGalasaApiComponents{c, namespace}
}

func (c *FakeGalasaV2alpha1) GalasaCpsComponents(namespace string) v2alpha1.GalasaCpsComponentInterface {
	return &FakeGalasaCpsComponents{c, namespace}
}

func (c *FakeGalasaV2alpha1) GalasaEcosystems(namespace string) v2alpha1.GalasaEcosystemInterface {
	return &FakeGalasaEcosystems{c, namespace}
}

func (c *FakeGalasaV2alpha1) GalasaEngineControllerComponents(namespace string) v2alpha1.GalasaEngineControllerComponentInterface {
	return &FakeGalasaEngineControllerComponents{c, namespace}
}

func (c *FakeGalasaV2alpha1) GalasaMetricsComponents(namespace string) v2alpha1.GalasaMetricsComponentInterface {
	return &FakeGalasaMetricsComponents{c, namespace}
}

func (c *FakeGalasaV2alpha1) GalasaRasComponents(namespace string) v2alpha1.GalasaRasComponentInterface {
	return &FakeGalasaRasComponents{c, namespace}
}

func (c *FakeGalasaV2alpha1) GalasaResmonComponents(namespace string) v2alpha1.GalasaResmonComponentInterface {
	return &FakeGalasaResmonComponents{c, namespace}
}

func (c *FakeGalasaV2alpha1) GalasaToolboxComponents(namespace string) v2alpha1.GalasaToolboxComponentInterface {
	return &FakeGalasaToolboxComponents{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeGalasaV2alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
