/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2alpha1 "github.com/galasa-dev/galasa-kubernetes-operator/pkg/apis/galasaecosystem/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGalasaMetricsComponents implements GalasaMetricsComponentInterface
type FakeGalasaMetricsComponents struct {
	Fake *FakeGalasaV2alpha1
	ns   string
}

var galasametricscomponentsResource = schema.GroupVersionResource{Group: "galasa.dev", Version: "v2alpha1", Resource: "galasametricscomponents"}

var galasametricscomponentsKind = schema.GroupVersionKind{Group: "galasa.dev", Version: "v2alpha1", Kind: "GalasaMetricsComponent"}

// Get takes name of the galasaMetricsComponent, and returns the corresponding galasaMetricsComponent object, and an error if there is any.
func (c *FakeGalasaMetricsComponents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.GalasaMetricsComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(galasametricscomponentsResource, c.ns, name), &v2alpha1.GalasaMetricsComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaMetricsComponent), err
}

// List takes label and field selectors, and returns the list of GalasaMetricsComponents that match those selectors.
func (c *FakeGalasaMetricsComponents) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.GalasaMetricsComponentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(galasametricscomponentsResource, galasametricscomponentsKind, c.ns, opts), &v2alpha1.GalasaMetricsComponentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2alpha1.GalasaMetricsComponentList{ListMeta: obj.(*v2alpha1.GalasaMetricsComponentList).ListMeta}
	for _, item := range obj.(*v2alpha1.GalasaMetricsComponentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested galasaMetricsComponents.
func (c *FakeGalasaMetricsComponents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(galasametricscomponentsResource, c.ns, opts))

}

// Create takes the representation of a galasaMetricsComponent and creates it.  Returns the server's representation of the galasaMetricsComponent, and an error, if there is any.
func (c *FakeGalasaMetricsComponents) Create(ctx context.Context, galasaMetricsComponent *v2alpha1.GalasaMetricsComponent, opts v1.CreateOptions) (result *v2alpha1.GalasaMetricsComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(galasametricscomponentsResource, c.ns, galasaMetricsComponent), &v2alpha1.GalasaMetricsComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaMetricsComponent), err
}

// Update takes the representation of a galasaMetricsComponent and updates it. Returns the server's representation of the galasaMetricsComponent, and an error, if there is any.
func (c *FakeGalasaMetricsComponents) Update(ctx context.Context, galasaMetricsComponent *v2alpha1.GalasaMetricsComponent, opts v1.UpdateOptions) (result *v2alpha1.GalasaMetricsComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(galasametricscomponentsResource, c.ns, galasaMetricsComponent), &v2alpha1.GalasaMetricsComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaMetricsComponent), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGalasaMetricsComponents) UpdateStatus(ctx context.Context, galasaMetricsComponent *v2alpha1.GalasaMetricsComponent, opts v1.UpdateOptions) (*v2alpha1.GalasaMetricsComponent, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(galasametricscomponentsResource, "status", c.ns, galasaMetricsComponent), &v2alpha1.GalasaMetricsComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaMetricsComponent), err
}

// Delete takes name of the galasaMetricsComponent and deletes it. Returns an error if one occurs.
func (c *FakeGalasaMetricsComponents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(galasametricscomponentsResource, c.ns, name), &v2alpha1.GalasaMetricsComponent{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGalasaMetricsComponents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(galasametricscomponentsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v2alpha1.GalasaMetricsComponentList{})
	return err
}

// Patch applies the patch and returns the patched galasaMetricsComponent.
func (c *FakeGalasaMetricsComponents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.GalasaMetricsComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(galasametricscomponentsResource, c.ns, name, pt, data, subresources...), &v2alpha1.GalasaMetricsComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaMetricsComponent), err
}
