/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2alpha1 "github.com/galasa-dev/kubernetes-operator/pkg/apis/galasaecosystem/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGalasaEcosystems implements GalasaEcosystemInterface
type FakeGalasaEcosystems struct {
	Fake *FakeGalasaV2alpha1
	ns   string
}

var galasaecosystemsResource = schema.GroupVersionResource{Group: "galasa.dev", Version: "v2alpha1", Resource: "galasaecosystems"}

var galasaecosystemsKind = schema.GroupVersionKind{Group: "galasa.dev", Version: "v2alpha1", Kind: "GalasaEcosystem"}

// Get takes name of the galasaEcosystem, and returns the corresponding galasaEcosystem object, and an error if there is any.
func (c *FakeGalasaEcosystems) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.GalasaEcosystem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(galasaecosystemsResource, c.ns, name), &v2alpha1.GalasaEcosystem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaEcosystem), err
}

// List takes label and field selectors, and returns the list of GalasaEcosystems that match those selectors.
func (c *FakeGalasaEcosystems) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.GalasaEcosystemList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(galasaecosystemsResource, galasaecosystemsKind, c.ns, opts), &v2alpha1.GalasaEcosystemList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2alpha1.GalasaEcosystemList{ListMeta: obj.(*v2alpha1.GalasaEcosystemList).ListMeta}
	for _, item := range obj.(*v2alpha1.GalasaEcosystemList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested galasaEcosystems.
func (c *FakeGalasaEcosystems) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(galasaecosystemsResource, c.ns, opts))

}

// Create takes the representation of a galasaEcosystem and creates it.  Returns the server's representation of the galasaEcosystem, and an error, if there is any.
func (c *FakeGalasaEcosystems) Create(ctx context.Context, galasaEcosystem *v2alpha1.GalasaEcosystem, opts v1.CreateOptions) (result *v2alpha1.GalasaEcosystem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(galasaecosystemsResource, c.ns, galasaEcosystem), &v2alpha1.GalasaEcosystem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaEcosystem), err
}

// Update takes the representation of a galasaEcosystem and updates it. Returns the server's representation of the galasaEcosystem, and an error, if there is any.
func (c *FakeGalasaEcosystems) Update(ctx context.Context, galasaEcosystem *v2alpha1.GalasaEcosystem, opts v1.UpdateOptions) (result *v2alpha1.GalasaEcosystem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(galasaecosystemsResource, c.ns, galasaEcosystem), &v2alpha1.GalasaEcosystem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaEcosystem), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGalasaEcosystems) UpdateStatus(ctx context.Context, galasaEcosystem *v2alpha1.GalasaEcosystem, opts v1.UpdateOptions) (*v2alpha1.GalasaEcosystem, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(galasaecosystemsResource, "status", c.ns, galasaEcosystem), &v2alpha1.GalasaEcosystem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaEcosystem), err
}

// Delete takes name of the galasaEcosystem and deletes it. Returns an error if one occurs.
func (c *FakeGalasaEcosystems) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(galasaecosystemsResource, c.ns, name), &v2alpha1.GalasaEcosystem{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGalasaEcosystems) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(galasaecosystemsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v2alpha1.GalasaEcosystemList{})
	return err
}

// Patch applies the patch and returns the patched galasaEcosystem.
func (c *FakeGalasaEcosystems) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.GalasaEcosystem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(galasaecosystemsResource, c.ns, name, pt, data, subresources...), &v2alpha1.GalasaEcosystem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.GalasaEcosystem), err
}
