/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	"fmt"

	v2alpha1 "github.com/galasa-dev/galasa-kubernetes-operator/pkg/apis/galasaecosystem/v2alpha1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=galasa.dev, Version=v2alpha1
	case v2alpha1.SchemeGroupVersion.WithResource("galasaapicomponents"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Galasa().V2alpha1().GalasaApiComponents().Informer()}, nil
	case v2alpha1.SchemeGroupVersion.WithResource("galasacpscomponents"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Galasa().V2alpha1().GalasaCpsComponents().Informer()}, nil
	case v2alpha1.SchemeGroupVersion.WithResource("galasaecosystems"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Galasa().V2alpha1().GalasaEcosystems().Informer()}, nil
	case v2alpha1.SchemeGroupVersion.WithResource("galasaenginecontrollercomponents"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Galasa().V2alpha1().GalasaEngineControllerComponents().Informer()}, nil
	case v2alpha1.SchemeGroupVersion.WithResource("galasametricscomponents"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Galasa().V2alpha1().GalasaMetricsComponents().Informer()}, nil
	case v2alpha1.SchemeGroupVersion.WithResource("galasarascomponents"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Galasa().V2alpha1().GalasaRasComponents().Informer()}, nil
	case v2alpha1.SchemeGroupVersion.WithResource("galasaresmoncomponents"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Galasa().V2alpha1().GalasaResmonComponents().Informer()}, nil
	case v2alpha1.SchemeGroupVersion.WithResource("galasatoolboxcomponents"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Galasa().V2alpha1().GalasaToolboxComponents().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
