/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	"context"
	"time"

	v2alpha1 "github.com/galasa-dev/galasa-kubernetes-operator/pkg/apis/galasaecosystem/v2alpha1"
	scheme "github.com/galasa-dev/galasa-kubernetes-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GalasaResmonComponentsGetter has a method to return a GalasaResmonComponentInterface.
// A group's client should implement this interface.
type GalasaResmonComponentsGetter interface {
	GalasaResmonComponents(namespace string) GalasaResmonComponentInterface
}

// GalasaResmonComponentInterface has methods to work with GalasaResmonComponent resources.
type GalasaResmonComponentInterface interface {
	Create(ctx context.Context, galasaResmonComponent *v2alpha1.GalasaResmonComponent, opts v1.CreateOptions) (*v2alpha1.GalasaResmonComponent, error)
	Update(ctx context.Context, galasaResmonComponent *v2alpha1.GalasaResmonComponent, opts v1.UpdateOptions) (*v2alpha1.GalasaResmonComponent, error)
	UpdateStatus(ctx context.Context, galasaResmonComponent *v2alpha1.GalasaResmonComponent, opts v1.UpdateOptions) (*v2alpha1.GalasaResmonComponent, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2alpha1.GalasaResmonComponent, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2alpha1.GalasaResmonComponentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.GalasaResmonComponent, err error)
	GalasaResmonComponentExpansion
}

// galasaResmonComponents implements GalasaResmonComponentInterface
type galasaResmonComponents struct {
	client rest.Interface
	ns     string
}

// newGalasaResmonComponents returns a GalasaResmonComponents
func newGalasaResmonComponents(c *GalasaV2alpha1Client, namespace string) *galasaResmonComponents {
	return &galasaResmonComponents{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the galasaResmonComponent, and returns the corresponding galasaResmonComponent object, and an error if there is any.
func (c *galasaResmonComponents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.GalasaResmonComponent, err error) {
	result = &v2alpha1.GalasaResmonComponent{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("galasaresmoncomponents").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GalasaResmonComponents that match those selectors.
func (c *galasaResmonComponents) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.GalasaResmonComponentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2alpha1.GalasaResmonComponentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("galasaresmoncomponents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested galasaResmonComponents.
func (c *galasaResmonComponents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("galasaresmoncomponents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a galasaResmonComponent and creates it.  Returns the server's representation of the galasaResmonComponent, and an error, if there is any.
func (c *galasaResmonComponents) Create(ctx context.Context, galasaResmonComponent *v2alpha1.GalasaResmonComponent, opts v1.CreateOptions) (result *v2alpha1.GalasaResmonComponent, err error) {
	result = &v2alpha1.GalasaResmonComponent{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("galasaresmoncomponents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(galasaResmonComponent).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a galasaResmonComponent and updates it. Returns the server's representation of the galasaResmonComponent, and an error, if there is any.
func (c *galasaResmonComponents) Update(ctx context.Context, galasaResmonComponent *v2alpha1.GalasaResmonComponent, opts v1.UpdateOptions) (result *v2alpha1.GalasaResmonComponent, err error) {
	result = &v2alpha1.GalasaResmonComponent{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("galasaresmoncomponents").
		Name(galasaResmonComponent.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(galasaResmonComponent).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *galasaResmonComponents) UpdateStatus(ctx context.Context, galasaResmonComponent *v2alpha1.GalasaResmonComponent, opts v1.UpdateOptions) (result *v2alpha1.GalasaResmonComponent, err error) {
	result = &v2alpha1.GalasaResmonComponent{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("galasaresmoncomponents").
		Name(galasaResmonComponent.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(galasaResmonComponent).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the galasaResmonComponent and deletes it. Returns an error if one occurs.
func (c *galasaResmonComponents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("galasaresmoncomponents").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *galasaResmonComponents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("galasaresmoncomponents").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched galasaResmonComponent.
func (c *galasaResmonComponents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.GalasaResmonComponent, err error) {
	result = &v2alpha1.GalasaResmonComponent{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("galasaresmoncomponents").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
