/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	"context"
	"time"

	v2alpha1 "github.com/galasa-dev/galasa-kubernetes-operator/pkg/apis/galasaecosystem/v2alpha1"
	scheme "github.com/galasa-dev/galasa-kubernetes-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GalasaCpsComponentsGetter has a method to return a GalasaCpsComponentInterface.
// A group's client should implement this interface.
type GalasaCpsComponentsGetter interface {
	GalasaCpsComponents(namespace string) GalasaCpsComponentInterface
}

// GalasaCpsComponentInterface has methods to work with GalasaCpsComponent resources.
type GalasaCpsComponentInterface interface {
	Create(ctx context.Context, galasaCpsComponent *v2alpha1.GalasaCpsComponent, opts v1.CreateOptions) (*v2alpha1.GalasaCpsComponent, error)
	Update(ctx context.Context, galasaCpsComponent *v2alpha1.GalasaCpsComponent, opts v1.UpdateOptions) (*v2alpha1.GalasaCpsComponent, error)
	UpdateStatus(ctx context.Context, galasaCpsComponent *v2alpha1.GalasaCpsComponent, opts v1.UpdateOptions) (*v2alpha1.GalasaCpsComponent, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2alpha1.GalasaCpsComponent, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2alpha1.GalasaCpsComponentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.GalasaCpsComponent, err error)
	GalasaCpsComponentExpansion
}

// galasaCpsComponents implements GalasaCpsComponentInterface
type galasaCpsComponents struct {
	client rest.Interface
	ns     string
}

// newGalasaCpsComponents returns a GalasaCpsComponents
func newGalasaCpsComponents(c *GalasaV2alpha1Client, namespace string) *galasaCpsComponents {
	return &galasaCpsComponents{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the galasaCpsComponent, and returns the corresponding galasaCpsComponent object, and an error if there is any.
func (c *galasaCpsComponents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.GalasaCpsComponent, err error) {
	result = &v2alpha1.GalasaCpsComponent{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("galasacpscomponents").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GalasaCpsComponents that match those selectors.
func (c *galasaCpsComponents) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.GalasaCpsComponentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2alpha1.GalasaCpsComponentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("galasacpscomponents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested galasaCpsComponents.
func (c *galasaCpsComponents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("galasacpscomponents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a galasaCpsComponent and creates it.  Returns the server's representation of the galasaCpsComponent, and an error, if there is any.
func (c *galasaCpsComponents) Create(ctx context.Context, galasaCpsComponent *v2alpha1.GalasaCpsComponent, opts v1.CreateOptions) (result *v2alpha1.GalasaCpsComponent, err error) {
	result = &v2alpha1.GalasaCpsComponent{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("galasacpscomponents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(galasaCpsComponent).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a galasaCpsComponent and updates it. Returns the server's representation of the galasaCpsComponent, and an error, if there is any.
func (c *galasaCpsComponents) Update(ctx context.Context, galasaCpsComponent *v2alpha1.GalasaCpsComponent, opts v1.UpdateOptions) (result *v2alpha1.GalasaCpsComponent, err error) {
	result = &v2alpha1.GalasaCpsComponent{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("galasacpscomponents").
		Name(galasaCpsComponent.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(galasaCpsComponent).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *galasaCpsComponents) UpdateStatus(ctx context.Context, galasaCpsComponent *v2alpha1.GalasaCpsComponent, opts v1.UpdateOptions) (result *v2alpha1.GalasaCpsComponent, err error) {
	result = &v2alpha1.GalasaCpsComponent{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("galasacpscomponents").
		Name(galasaCpsComponent.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(galasaCpsComponent).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the galasaCpsComponent and deletes it. Returns an error if one occurs.
func (c *galasaCpsComponents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("galasacpscomponents").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *galasaCpsComponents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("galasacpscomponents").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched galasaCpsComponent.
func (c *galasaCpsComponents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.GalasaCpsComponent, err error) {
	result = &v2alpha1.GalasaCpsComponent{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("galasacpscomponents").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
