/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	"context"
	"time"

	v2alpha1 "github.com/galasa-dev/kubernetes-operator/pkg/apis/galasaecosystem/v2alpha1"
	scheme "github.com/galasa-dev/kubernetes-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GalasaApiComponentsGetter has a method to return a GalasaApiComponentInterface.
// A group's client should implement this interface.
type GalasaApiComponentsGetter interface {
	GalasaApiComponents(namespace string) GalasaApiComponentInterface
}

// GalasaApiComponentInterface has methods to work with GalasaApiComponent resources.
type GalasaApiComponentInterface interface {
	Create(ctx context.Context, galasaApiComponent *v2alpha1.GalasaApiComponent, opts v1.CreateOptions) (*v2alpha1.GalasaApiComponent, error)
	Update(ctx context.Context, galasaApiComponent *v2alpha1.GalasaApiComponent, opts v1.UpdateOptions) (*v2alpha1.GalasaApiComponent, error)
	UpdateStatus(ctx context.Context, galasaApiComponent *v2alpha1.GalasaApiComponent, opts v1.UpdateOptions) (*v2alpha1.GalasaApiComponent, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2alpha1.GalasaApiComponent, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2alpha1.GalasaApiComponentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.GalasaApiComponent, err error)
	GalasaApiComponentExpansion
}

// galasaApiComponents implements GalasaApiComponentInterface
type galasaApiComponents struct {
	client rest.Interface
	ns     string
}

// newGalasaApiComponents returns a GalasaApiComponents
func newGalasaApiComponents(c *GalasaV2alpha1Client, namespace string) *galasaApiComponents {
	return &galasaApiComponents{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the galasaApiComponent, and returns the corresponding galasaApiComponent object, and an error if there is any.
func (c *galasaApiComponents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.GalasaApiComponent, err error) {
	result = &v2alpha1.GalasaApiComponent{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("galasaapicomponents").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GalasaApiComponents that match those selectors.
func (c *galasaApiComponents) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.GalasaApiComponentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2alpha1.GalasaApiComponentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("galasaapicomponents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested galasaApiComponents.
func (c *galasaApiComponents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("galasaapicomponents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a galasaApiComponent and creates it.  Returns the server's representation of the galasaApiComponent, and an error, if there is any.
func (c *galasaApiComponents) Create(ctx context.Context, galasaApiComponent *v2alpha1.GalasaApiComponent, opts v1.CreateOptions) (result *v2alpha1.GalasaApiComponent, err error) {
	result = &v2alpha1.GalasaApiComponent{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("galasaapicomponents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(galasaApiComponent).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a galasaApiComponent and updates it. Returns the server's representation of the galasaApiComponent, and an error, if there is any.
func (c *galasaApiComponents) Update(ctx context.Context, galasaApiComponent *v2alpha1.GalasaApiComponent, opts v1.UpdateOptions) (result *v2alpha1.GalasaApiComponent, err error) {
	result = &v2alpha1.GalasaApiComponent{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("galasaapicomponents").
		Name(galasaApiComponent.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(galasaApiComponent).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *galasaApiComponents) UpdateStatus(ctx context.Context, galasaApiComponent *v2alpha1.GalasaApiComponent, opts v1.UpdateOptions) (result *v2alpha1.GalasaApiComponent, err error) {
	result = &v2alpha1.GalasaApiComponent{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("galasaapicomponents").
		Name(galasaApiComponent.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(galasaApiComponent).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the galasaApiComponent and deletes it. Returns an error if one occurs.
func (c *galasaApiComponents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("galasaapicomponents").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *galasaApiComponents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("galasaapicomponents").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched galasaApiComponent.
func (c *galasaApiComponents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.GalasaApiComponent, err error) {
	result = &v2alpha1.GalasaApiComponent{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("galasaapicomponents").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
