/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	"context"
	"time"

	v2alpha1 "github.com/galasa-dev/kubernetes-operator/pkg/apis/galasaecosystem/v2alpha1"
	scheme "github.com/galasa-dev/kubernetes-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GalasaEcosystemsGetter has a method to return a GalasaEcosystemInterface.
// A group's client should implement this interface.
type GalasaEcosystemsGetter interface {
	GalasaEcosystems(namespace string) GalasaEcosystemInterface
}

// GalasaEcosystemInterface has methods to work with GalasaEcosystem resources.
type GalasaEcosystemInterface interface {
	Create(ctx context.Context, galasaEcosystem *v2alpha1.GalasaEcosystem, opts v1.CreateOptions) (*v2alpha1.GalasaEcosystem, error)
	Update(ctx context.Context, galasaEcosystem *v2alpha1.GalasaEcosystem, opts v1.UpdateOptions) (*v2alpha1.GalasaEcosystem, error)
	UpdateStatus(ctx context.Context, galasaEcosystem *v2alpha1.GalasaEcosystem, opts v1.UpdateOptions) (*v2alpha1.GalasaEcosystem, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2alpha1.GalasaEcosystem, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2alpha1.GalasaEcosystemList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.GalasaEcosystem, err error)
	GalasaEcosystemExpansion
}

// galasaEcosystems implements GalasaEcosystemInterface
type galasaEcosystems struct {
	client rest.Interface
	ns     string
}

// newGalasaEcosystems returns a GalasaEcosystems
func newGalasaEcosystems(c *GalasaV2alpha1Client, namespace string) *galasaEcosystems {
	return &galasaEcosystems{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the galasaEcosystem, and returns the corresponding galasaEcosystem object, and an error if there is any.
func (c *galasaEcosystems) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.GalasaEcosystem, err error) {
	result = &v2alpha1.GalasaEcosystem{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("galasaecosystems").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GalasaEcosystems that match those selectors.
func (c *galasaEcosystems) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.GalasaEcosystemList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2alpha1.GalasaEcosystemList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("galasaecosystems").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested galasaEcosystems.
func (c *galasaEcosystems) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("galasaecosystems").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a galasaEcosystem and creates it.  Returns the server's representation of the galasaEcosystem, and an error, if there is any.
func (c *galasaEcosystems) Create(ctx context.Context, galasaEcosystem *v2alpha1.GalasaEcosystem, opts v1.CreateOptions) (result *v2alpha1.GalasaEcosystem, err error) {
	result = &v2alpha1.GalasaEcosystem{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("galasaecosystems").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(galasaEcosystem).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a galasaEcosystem and updates it. Returns the server's representation of the galasaEcosystem, and an error, if there is any.
func (c *galasaEcosystems) Update(ctx context.Context, galasaEcosystem *v2alpha1.GalasaEcosystem, opts v1.UpdateOptions) (result *v2alpha1.GalasaEcosystem, err error) {
	result = &v2alpha1.GalasaEcosystem{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("galasaecosystems").
		Name(galasaEcosystem.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(galasaEcosystem).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *galasaEcosystems) UpdateStatus(ctx context.Context, galasaEcosystem *v2alpha1.GalasaEcosystem, opts v1.UpdateOptions) (result *v2alpha1.GalasaEcosystem, err error) {
	result = &v2alpha1.GalasaEcosystem{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("galasaecosystems").
		Name(galasaEcosystem.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(galasaEcosystem).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the galasaEcosystem and deletes it. Returns an error if one occurs.
func (c *galasaEcosystems) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("galasaecosystems").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *galasaEcosystems) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("galasaecosystems").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched galasaEcosystem.
func (c *galasaEcosystems) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.GalasaEcosystem, err error) {
	result = &v2alpha1.GalasaEcosystem{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("galasaecosystems").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
