/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	"context"
	"time"

	v2alpha1 "github.com/galasa-dev/kubernetes-operator/pkg/apis/galasaecosystem/v2alpha1"
	scheme "github.com/galasa-dev/kubernetes-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GalasaRasComponentsGetter has a method to return a GalasaRasComponentInterface.
// A group's client should implement this interface.
type GalasaRasComponentsGetter interface {
	GalasaRasComponents(namespace string) GalasaRasComponentInterface
}

// GalasaRasComponentInterface has methods to work with GalasaRasComponent resources.
type GalasaRasComponentInterface interface {
	Create(ctx context.Context, galasaRasComponent *v2alpha1.GalasaRasComponent, opts v1.CreateOptions) (*v2alpha1.GalasaRasComponent, error)
	Update(ctx context.Context, galasaRasComponent *v2alpha1.GalasaRasComponent, opts v1.UpdateOptions) (*v2alpha1.GalasaRasComponent, error)
	UpdateStatus(ctx context.Context, galasaRasComponent *v2alpha1.GalasaRasComponent, opts v1.UpdateOptions) (*v2alpha1.GalasaRasComponent, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2alpha1.GalasaRasComponent, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2alpha1.GalasaRasComponentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.GalasaRasComponent, err error)
	GalasaRasComponentExpansion
}

// galasaRasComponents implements GalasaRasComponentInterface
type galasaRasComponents struct {
	client rest.Interface
	ns     string
}

// newGalasaRasComponents returns a GalasaRasComponents
func newGalasaRasComponents(c *GalasaV2alpha1Client, namespace string) *galasaRasComponents {
	return &galasaRasComponents{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the galasaRasComponent, and returns the corresponding galasaRasComponent object, and an error if there is any.
func (c *galasaRasComponents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.GalasaRasComponent, err error) {
	result = &v2alpha1.GalasaRasComponent{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("galasarascomponents").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GalasaRasComponents that match those selectors.
func (c *galasaRasComponents) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.GalasaRasComponentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2alpha1.GalasaRasComponentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("galasarascomponents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested galasaRasComponents.
func (c *galasaRasComponents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("galasarascomponents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a galasaRasComponent and creates it.  Returns the server's representation of the galasaRasComponent, and an error, if there is any.
func (c *galasaRasComponents) Create(ctx context.Context, galasaRasComponent *v2alpha1.GalasaRasComponent, opts v1.CreateOptions) (result *v2alpha1.GalasaRasComponent, err error) {
	result = &v2alpha1.GalasaRasComponent{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("galasarascomponents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(galasaRasComponent).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a galasaRasComponent and updates it. Returns the server's representation of the galasaRasComponent, and an error, if there is any.
func (c *galasaRasComponents) Update(ctx context.Context, galasaRasComponent *v2alpha1.GalasaRasComponent, opts v1.UpdateOptions) (result *v2alpha1.GalasaRasComponent, err error) {
	result = &v2alpha1.GalasaRasComponent{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("galasarascomponents").
		Name(galasaRasComponent.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(galasaRasComponent).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *galasaRasComponents) UpdateStatus(ctx context.Context, galasaRasComponent *v2alpha1.GalasaRasComponent, opts v1.UpdateOptions) (result *v2alpha1.GalasaRasComponent, err error) {
	result = &v2alpha1.GalasaRasComponent{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("galasarascomponents").
		Name(galasaRasComponent.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(galasaRasComponent).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the galasaRasComponent and deletes it. Returns an error if one occurs.
func (c *galasaRasComponents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("galasarascomponents").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *galasaRasComponents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("galasarascomponents").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched galasaRasComponent.
func (c *galasaRasComponents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.GalasaRasComponent, err error) {
	result = &v2alpha1.GalasaRasComponent{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("galasarascomponents").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
