/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

type GalasaApiComponentExpansion interface{}

type GalasaCpsComponentExpansion interface{}

type GalasaEcosystemExpansion interface{}

type GalasaEngineControllerComponentExpansion interface{}

type GalasaMetricsComponentExpansion interface{}

type GalasaRasComponentExpansion interface{}

type GalasaResmonComponentExpansion interface{}

type GalasaToolboxComponentExpansion interface{}
