#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1alpha1
kind: SCMPoll
metadata:
  name: kubernetes-operator-pr-poll
  namespace: galasa-tekton
spec:
  metadata:
    name: kubernetes-operator-pr-poll
  description: Polls for PRs to the main branch
  pollFrequency: 30
  tidy: true
  concurrentPipelines: false
  repositories:
    - name: kubernetes-operator
      type: github-pr
      serviceAccountName: poll-sa
      params:
      - name: url
        value: https://api.github.com/repos/galasa-dev/galasa-kubernetes-operator
      - name: rebuildString
        value: "rebuild"
  pipelineRunSpec:
    params:
    - name: distBranch
      value: main
    - name: refspec
      value: $(kubernetes-operator.refSpec)
    - name: noPush
      value: "--no-push"
    pipelineRef:
      name: kubernetes-operator-pipeline
    serviceAccountName: build-bot
    podTemplate:
      nodeSelector:
        kubernetes.io/arch: amd64
        platform: hdc
    workspaces:
    - name: git-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi