/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

// GalasaApiComponentListerExpansion allows custom methods to be added to
// GalasaApiComponentLister.
type GalasaApiComponentListerExpansion interface{}

// GalasaApiComponentNamespaceListerExpansion allows custom methods to be added to
// GalasaApiComponentNamespaceLister.
type GalasaApiComponentNamespaceListerExpansion interface{}

// GalasaCpsComponentListerExpansion allows custom methods to be added to
// GalasaCpsComponentLister.
type GalasaCpsComponentListerExpansion interface{}

// GalasaCpsComponentNamespaceListerExpansion allows custom methods to be added to
// GalasaCpsComponentNamespaceLister.
type GalasaCpsComponentNamespaceListerExpansion interface{}

// GalasaEcosystemListerExpansion allows custom methods to be added to
// GalasaEcosystemLister.
type GalasaEcosystemListerExpansion interface{}

// GalasaEcosystemNamespaceListerExpansion allows custom methods to be added to
// GalasaEcosystemNamespaceLister.
type GalasaEcosystemNamespaceListerExpansion interface{}

// GalasaEngineControllerComponentListerExpansion allows custom methods to be added to
// GalasaEngineControllerComponentLister.
type GalasaEngineControllerComponentListerExpansion interface{}

// GalasaEngineControllerComponentNamespaceListerExpansion allows custom methods to be added to
// GalasaEngineControllerComponentNamespaceLister.
type GalasaEngineControllerComponentNamespaceListerExpansion interface{}

// GalasaMetricsComponentListerExpansion allows custom methods to be added to
// GalasaMetricsComponentLister.
type GalasaMetricsComponentListerExpansion interface{}

// GalasaMetricsComponentNamespaceListerExpansion allows custom methods to be added to
// GalasaMetricsComponentNamespaceLister.
type GalasaMetricsComponentNamespaceListerExpansion interface{}

// GalasaRasComponentListerExpansion allows custom methods to be added to
// GalasaRasComponentLister.
type GalasaRasComponentListerExpansion interface{}

// GalasaRasComponentNamespaceListerExpansion allows custom methods to be added to
// GalasaRasComponentNamespaceLister.
type GalasaRasComponentNamespaceListerExpansion interface{}

// GalasaResmonComponentListerExpansion allows custom methods to be added to
// GalasaResmonComponentLister.
type GalasaResmonComponentListerExpansion interface{}

// GalasaResmonComponentNamespaceListerExpansion allows custom methods to be added to
// GalasaResmonComponentNamespaceLister.
type GalasaResmonComponentNamespaceListerExpansion interface{}

// GalasaToolboxComponentListerExpansion allows custom methods to be added to
// GalasaToolboxComponentLister.
type GalasaToolboxComponentListerExpansion interface{}

// GalasaToolboxComponentNamespaceListerExpansion allows custom methods to be added to
// GalasaToolboxComponentNamespaceLister.
type GalasaToolboxComponentNamespaceListerExpansion interface{}
