/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	v2alpha1 "github.com/galasa-dev/kubernetes-operator/pkg/apis/galasaecosystem/v2alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GalasaMetricsComponentLister helps list GalasaMetricsComponents.
// All objects returned here must be treated as read-only.
type GalasaMetricsComponentLister interface {
	// List lists all GalasaMetricsComponents in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.GalasaMetricsComponent, err error)
	// GalasaMetricsComponents returns an object that can list and get GalasaMetricsComponents.
	GalasaMetricsComponents(namespace string) GalasaMetricsComponentNamespaceLister
	GalasaMetricsComponentListerExpansion
}

// galasaMetricsComponentLister implements the GalasaMetricsComponentLister interface.
type galasaMetricsComponentLister struct {
	indexer cache.Indexer
}

// NewGalasaMetricsComponentLister returns a new GalasaMetricsComponentLister.
func NewGalasaMetricsComponentLister(indexer cache.Indexer) GalasaMetricsComponentLister {
	return &galasaMetricsComponentLister{indexer: indexer}
}

// List lists all GalasaMetricsComponents in the indexer.
func (s *galasaMetricsComponentLister) List(selector labels.Selector) (ret []*v2alpha1.GalasaMetricsComponent, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.GalasaMetricsComponent))
	})
	return ret, err
}

// GalasaMetricsComponents returns an object that can list and get GalasaMetricsComponents.
func (s *galasaMetricsComponentLister) GalasaMetricsComponents(namespace string) GalasaMetricsComponentNamespaceLister {
	return galasaMetricsComponentNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// GalasaMetricsComponentNamespaceLister helps list and get GalasaMetricsComponents.
// All objects returned here must be treated as read-only.
type GalasaMetricsComponentNamespaceLister interface {
	// List lists all GalasaMetricsComponents in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.GalasaMetricsComponent, err error)
	// Get retrieves the GalasaMetricsComponent from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2alpha1.GalasaMetricsComponent, error)
	GalasaMetricsComponentNamespaceListerExpansion
}

// galasaMetricsComponentNamespaceLister implements the GalasaMetricsComponentNamespaceLister
// interface.
type galasaMetricsComponentNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all GalasaMetricsComponents in the indexer for a given namespace.
func (s galasaMetricsComponentNamespaceLister) List(selector labels.Selector) (ret []*v2alpha1.GalasaMetricsComponent, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.GalasaMetricsComponent))
	})
	return ret, err
}

// Get retrieves the GalasaMetricsComponent from the indexer for a given namespace and name.
func (s galasaMetricsComponentNamespaceLister) Get(name string) (*v2alpha1.GalasaMetricsComponent, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v2alpha1.Resource("galasametricscomponent"), name)
	}
	return obj.(*v2alpha1.GalasaMetricsComponent), nil
}
