/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	v2alpha1 "github.com/galasa-dev/galasa-kubernetes-operator/pkg/apis/galasaecosystem/v2alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GalasaCpsComponentLister helps list GalasaCpsComponents.
// All objects returned here must be treated as read-only.
type GalasaCpsComponentLister interface {
	// List lists all GalasaCpsComponents in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.GalasaCpsComponent, err error)
	// GalasaCpsComponents returns an object that can list and get GalasaCpsComponents.
	GalasaCpsComponents(namespace string) GalasaCpsComponentNamespaceLister
	GalasaCpsComponentListerExpansion
}

// galasaCpsComponentLister implements the GalasaCpsComponentLister interface.
type galasaCpsComponentLister struct {
	indexer cache.Indexer
}

// NewGalasaCpsComponentLister returns a new GalasaCpsComponentLister.
func NewGalasaCpsComponentLister(indexer cache.Indexer) GalasaCpsComponentLister {
	return &galasaCpsComponentLister{indexer: indexer}
}

// List lists all GalasaCpsComponents in the indexer.
func (s *galasaCpsComponentLister) List(selector labels.Selector) (ret []*v2alpha1.GalasaCpsComponent, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.GalasaCpsComponent))
	})
	return ret, err
}

// GalasaCpsComponents returns an object that can list and get GalasaCpsComponents.
func (s *galasaCpsComponentLister) GalasaCpsComponents(namespace string) GalasaCpsComponentNamespaceLister {
	return galasaCpsComponentNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// GalasaCpsComponentNamespaceLister helps list and get GalasaCpsComponents.
// All objects returned here must be treated as read-only.
type GalasaCpsComponentNamespaceLister interface {
	// List lists all GalasaCpsComponents in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.GalasaCpsComponent, err error)
	// Get retrieves the GalasaCpsComponent from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2alpha1.GalasaCpsComponent, error)
	GalasaCpsComponentNamespaceListerExpansion
}

// galasaCpsComponentNamespaceLister implements the GalasaCpsComponentNamespaceLister
// interface.
type galasaCpsComponentNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all GalasaCpsComponents in the indexer for a given namespace.
func (s galasaCpsComponentNamespaceLister) List(selector labels.Selector) (ret []*v2alpha1.GalasaCpsComponent, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.GalasaCpsComponent))
	})
	return ret, err
}

// Get retrieves the GalasaCpsComponent from the indexer for a given namespace and name.
func (s galasaCpsComponentNamespaceLister) Get(name string) (*v2alpha1.GalasaCpsComponent, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v2alpha1.Resource("galasacpscomponent"), name)
	}
	return obj.(*v2alpha1.GalasaCpsComponent), nil
}
