/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	v2alpha1 "github.com/galasa-dev/kubernetes-operator/pkg/apis/galasaecosystem/v2alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GalasaResmonComponentLister helps list GalasaResmonComponents.
// All objects returned here must be treated as read-only.
type GalasaResmonComponentLister interface {
	// List lists all GalasaResmonComponents in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.GalasaResmonComponent, err error)
	// GalasaResmonComponents returns an object that can list and get GalasaResmonComponents.
	GalasaResmonComponents(namespace string) GalasaResmonComponentNamespaceLister
	GalasaResmonComponentListerExpansion
}

// galasaResmonComponentLister implements the GalasaResmonComponentLister interface.
type galasaResmonComponentLister struct {
	indexer cache.Indexer
}

// NewGalasaResmonComponentLister returns a new GalasaResmonComponentLister.
func NewGalasaResmonComponentLister(indexer cache.Indexer) GalasaResmonComponentLister {
	return &galasaResmonComponentLister{indexer: indexer}
}

// List lists all GalasaResmonComponents in the indexer.
func (s *galasaResmonComponentLister) List(selector labels.Selector) (ret []*v2alpha1.GalasaResmonComponent, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.GalasaResmonComponent))
	})
	return ret, err
}

// GalasaResmonComponents returns an object that can list and get GalasaResmonComponents.
func (s *galasaResmonComponentLister) GalasaResmonComponents(namespace string) GalasaResmonComponentNamespaceLister {
	return galasaResmonComponentNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// GalasaResmonComponentNamespaceLister helps list and get GalasaResmonComponents.
// All objects returned here must be treated as read-only.
type GalasaResmonComponentNamespaceLister interface {
	// List lists all GalasaResmonComponents in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.GalasaResmonComponent, err error)
	// Get retrieves the GalasaResmonComponent from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2alpha1.GalasaResmonComponent, error)
	GalasaResmonComponentNamespaceListerExpansion
}

// galasaResmonComponentNamespaceLister implements the GalasaResmonComponentNamespaceLister
// interface.
type galasaResmonComponentNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all GalasaResmonComponents in the indexer for a given namespace.
func (s galasaResmonComponentNamespaceLister) List(selector labels.Selector) (ret []*v2alpha1.GalasaResmonComponent, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.GalasaResmonComponent))
	})
	return ret, err
}

// Get retrieves the GalasaResmonComponent from the indexer for a given namespace and name.
func (s galasaResmonComponentNamespaceLister) Get(name string) (*v2alpha1.GalasaResmonComponent, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v2alpha1.Resource("galasaresmoncomponent"), name)
	}
	return obj.(*v2alpha1.GalasaResmonComponent), nil
}
