/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	v2alpha1 "github.com/galasa-dev/galasa-kubernetes-operator/pkg/apis/galasaecosystem/v2alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GalasaRasComponentLister helps list GalasaRasComponents.
// All objects returned here must be treated as read-only.
type GalasaRasComponentLister interface {
	// List lists all GalasaRasComponents in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.GalasaRasComponent, err error)
	// GalasaRasComponents returns an object that can list and get GalasaRasComponents.
	GalasaRasComponents(namespace string) GalasaRasComponentNamespaceLister
	GalasaRasComponentListerExpansion
}

// galasaRasComponentLister implements the GalasaRasComponentLister interface.
type galasaRasComponentLister struct {
	indexer cache.Indexer
}

// NewGalasaRasComponentLister returns a new GalasaRasComponentLister.
func NewGalasaRasComponentLister(indexer cache.Indexer) GalasaRasComponentLister {
	return &galasaRasComponentLister{indexer: indexer}
}

// List lists all GalasaRasComponents in the indexer.
func (s *galasaRasComponentLister) List(selector labels.Selector) (ret []*v2alpha1.GalasaRasComponent, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.GalasaRasComponent))
	})
	return ret, err
}

// GalasaRasComponents returns an object that can list and get GalasaRasComponents.
func (s *galasaRasComponentLister) GalasaRasComponents(namespace string) GalasaRasComponentNamespaceLister {
	return galasaRasComponentNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// GalasaRasComponentNamespaceLister helps list and get GalasaRasComponents.
// All objects returned here must be treated as read-only.
type GalasaRasComponentNamespaceLister interface {
	// List lists all GalasaRasComponents in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.GalasaRasComponent, err error)
	// Get retrieves the GalasaRasComponent from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2alpha1.GalasaRasComponent, error)
	GalasaRasComponentNamespaceListerExpansion
}

// galasaRasComponentNamespaceLister implements the GalasaRasComponentNamespaceLister
// interface.
type galasaRasComponentNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all GalasaRasComponents in the indexer for a given namespace.
func (s galasaRasComponentNamespaceLister) List(selector labels.Selector) (ret []*v2alpha1.GalasaRasComponent, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.GalasaRasComponent))
	})
	return ret, err
}

// Get retrieves the GalasaRasComponent from the indexer for a given namespace and name.
func (s galasaRasComponentNamespaceLister) Get(name string) (*v2alpha1.GalasaRasComponent, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v2alpha1.Resource("galasarascomponent"), name)
	}
	return obj.(*v2alpha1.GalasaRasComponent), nil
}
