/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	v2alpha1 "github.com/galasa-dev/kubernetes-operator/pkg/apis/galasaecosystem/v2alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GalasaEcosystemLister helps list GalasaEcosystems.
// All objects returned here must be treated as read-only.
type GalasaEcosystemLister interface {
	// List lists all GalasaEcosystems in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.GalasaEcosystem, err error)
	// GalasaEcosystems returns an object that can list and get GalasaEcosystems.
	GalasaEcosystems(namespace string) GalasaEcosystemNamespaceLister
	GalasaEcosystemListerExpansion
}

// galasaEcosystemLister implements the GalasaEcosystemLister interface.
type galasaEcosystemLister struct {
	indexer cache.Indexer
}

// NewGalasaEcosystemLister returns a new GalasaEcosystemLister.
func NewGalasaEcosystemLister(indexer cache.Indexer) GalasaEcosystemLister {
	return &galasaEcosystemLister{indexer: indexer}
}

// List lists all GalasaEcosystems in the indexer.
func (s *galasaEcosystemLister) List(selector labels.Selector) (ret []*v2alpha1.GalasaEcosystem, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.GalasaEcosystem))
	})
	return ret, err
}

// GalasaEcosystems returns an object that can list and get GalasaEcosystems.
func (s *galasaEcosystemLister) GalasaEcosystems(namespace string) GalasaEcosystemNamespaceLister {
	return galasaEcosystemNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// GalasaEcosystemNamespaceLister helps list and get GalasaEcosystems.
// All objects returned here must be treated as read-only.
type GalasaEcosystemNamespaceLister interface {
	// List lists all GalasaEcosystems in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.GalasaEcosystem, err error)
	// Get retrieves the GalasaEcosystem from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2alpha1.GalasaEcosystem, error)
	GalasaEcosystemNamespaceListerExpansion
}

// galasaEcosystemNamespaceLister implements the GalasaEcosystemNamespaceLister
// interface.
type galasaEcosystemNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all GalasaEcosystems in the indexer for a given namespace.
func (s galasaEcosystemNamespaceLister) List(selector labels.Selector) (ret []*v2alpha1.GalasaEcosystem, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.GalasaEcosystem))
	})
	return ret, err
}

// Get retrieves the GalasaEcosystem from the indexer for a given namespace and name.
func (s galasaEcosystemNamespaceLister) Get(name string) (*v2alpha1.GalasaEcosystem, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v2alpha1.Resource("galasaecosystem"), name)
	}
	return obj.(*v2alpha1.GalasaEcosystem), nil
}
