/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	v2alpha1 "github.com/galasa-dev/kubernetes-operator/pkg/apis/galasaecosystem/v2alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GalasaEngineControllerComponentLister helps list GalasaEngineControllerComponents.
// All objects returned here must be treated as read-only.
type GalasaEngineControllerComponentLister interface {
	// List lists all GalasaEngineControllerComponents in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.GalasaEngineControllerComponent, err error)
	// GalasaEngineControllerComponents returns an object that can list and get GalasaEngineControllerComponents.
	GalasaEngineControllerComponents(namespace string) GalasaEngineControllerComponentNamespaceLister
	GalasaEngineControllerComponentListerExpansion
}

// galasaEngineControllerComponentLister implements the GalasaEngineControllerComponentLister interface.
type galasaEngineControllerComponentLister struct {
	indexer cache.Indexer
}

// NewGalasaEngineControllerComponentLister returns a new GalasaEngineControllerComponentLister.
func NewGalasaEngineControllerComponentLister(indexer cache.Indexer) GalasaEngineControllerComponentLister {
	return &galasaEngineControllerComponentLister{indexer: indexer}
}

// List lists all GalasaEngineControllerComponents in the indexer.
func (s *galasaEngineControllerComponentLister) List(selector labels.Selector) (ret []*v2alpha1.GalasaEngineControllerComponent, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.GalasaEngineControllerComponent))
	})
	return ret, err
}

// GalasaEngineControllerComponents returns an object that can list and get GalasaEngineControllerComponents.
func (s *galasaEngineControllerComponentLister) GalasaEngineControllerComponents(namespace string) GalasaEngineControllerComponentNamespaceLister {
	return galasaEngineControllerComponentNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// GalasaEngineControllerComponentNamespaceLister helps list and get GalasaEngineControllerComponents.
// All objects returned here must be treated as read-only.
type GalasaEngineControllerComponentNamespaceLister interface {
	// List lists all GalasaEngineControllerComponents in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.GalasaEngineControllerComponent, err error)
	// Get retrieves the GalasaEngineControllerComponent from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2alpha1.GalasaEngineControllerComponent, error)
	GalasaEngineControllerComponentNamespaceListerExpansion
}

// galasaEngineControllerComponentNamespaceLister implements the GalasaEngineControllerComponentNamespaceLister
// interface.
type galasaEngineControllerComponentNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all GalasaEngineControllerComponents in the indexer for a given namespace.
func (s galasaEngineControllerComponentNamespaceLister) List(selector labels.Selector) (ret []*v2alpha1.GalasaEngineControllerComponent, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.GalasaEngineControllerComponent))
	})
	return ret, err
}

// Get retrieves the GalasaEngineControllerComponent from the indexer for a given namespace and name.
func (s galasaEngineControllerComponentNamespaceLister) Get(name string) (*v2alpha1.GalasaEngineControllerComponent, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v2alpha1.Resource("galasaenginecontrollercomponent"), name)
	}
	return obj.(*v2alpha1.GalasaEngineControllerComponent), nil
}
