/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by informer-gen. DO NOT EDIT.

package v2alpha1

import (
	internalinterfaces "github.com/galasa-dev/galasa-kubernetes-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// GalasaApiComponents returns a GalasaApiComponentInformer.
	GalasaApiComponents() GalasaApiComponentInformer
	// GalasaCpsComponents returns a GalasaCpsComponentInformer.
	GalasaCpsComponents() GalasaCpsComponentInformer
	// GalasaEcosystems returns a GalasaEcosystemInformer.
	GalasaEcosystems() GalasaEcosystemInformer
	// GalasaEngineControllerComponents returns a GalasaEngineControllerComponentInformer.
	GalasaEngineControllerComponents() GalasaEngineControllerComponentInformer
	// GalasaMetricsComponents returns a GalasaMetricsComponentInformer.
	GalasaMetricsComponents() GalasaMetricsComponentInformer
	// GalasaRasComponents returns a GalasaRasComponentInformer.
	GalasaRasComponents() GalasaRasComponentInformer
	// GalasaResmonComponents returns a GalasaResmonComponentInformer.
	GalasaResmonComponents() GalasaResmonComponentInformer
	// GalasaToolboxComponents returns a GalasaToolboxComponentInformer.
	GalasaToolboxComponents() GalasaToolboxComponentInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// GalasaApiComponents returns a GalasaApiComponentInformer.
func (v *version) GalasaApiComponents() GalasaApiComponentInformer {
	return &galasaApiComponentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// GalasaCpsComponents returns a GalasaCpsComponentInformer.
func (v *version) GalasaCpsComponents() GalasaCpsComponentInformer {
	return &galasaCpsComponentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// GalasaEcosystems returns a GalasaEcosystemInformer.
func (v *version) GalasaEcosystems() GalasaEcosystemInformer {
	return &galasaEcosystemInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// GalasaEngineControllerComponents returns a GalasaEngineControllerComponentInformer.
func (v *version) GalasaEngineControllerComponents() GalasaEngineControllerComponentInformer {
	return &galasaEngineControllerComponentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// GalasaMetricsComponents returns a GalasaMetricsComponentInformer.
func (v *version) GalasaMetricsComponents() GalasaMetricsComponentInformer {
	return &galasaMetricsComponentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// GalasaRasComponents returns a GalasaRasComponentInformer.
func (v *version) GalasaRasComponents() GalasaRasComponentInformer {
	return &galasaRasComponentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// GalasaResmonComponents returns a GalasaResmonComponentInformer.
func (v *version) GalasaResmonComponents() GalasaResmonComponentInformer {
	return &galasaResmonComponentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// GalasaToolboxComponents returns a GalasaToolboxComponentInformer.
func (v *version) GalasaToolboxComponents() GalasaToolboxComponentInformer {
	return &galasaToolboxComponentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
