/*
 * Copyright contributors to the Galasa Project
 */
// Code generated by injection-gen. DO NOT EDIT.

package fake

import (
	context "context"

	fake "github.com/galasa-dev/kubernetes-operator/pkg/client/injection/informers/factory/fake"
	galasaenginecontrollercomponent "github.com/galasa-dev/kubernetes-operator/pkg/client/injection/informers/galasaecosystem/v2alpha1/galasaenginecontrollercomponent"
	controller "knative.dev/pkg/controller"
	injection "knative.dev/pkg/injection"
)

var Get = galasaenginecontrollercomponent.Get

func init() {
	injection.Fake.RegisterInformer(withInformer)
}

func withInformer(ctx context.Context) (context.Context, controller.Informer) {
	f := fake.Get(ctx)
	inf := f.Galasa().V2alpha1().GalasaEngineControllerComponents()
	return context.WithValue(ctx, galasaenginecontrollercomponent.Key{}, inf), inf.Informer()
}
